baseURL = "/"
title = "LUDIK"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "LUDIK" # title for frontpage, may include image
copyright = "Konstantina Angeletou"
description = ""
#startbuttonText = ""
#startbuttonLink = ""
#custom_css = "foo.css"

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/posts/'
title = "Posts"

[params.one]
enable = true
title = 'Arcu aliquet vel lobortis ata nisl<br />eget augue amet aliquet nisl cep donec'
body = 'Aliquam ut ex ut augue consectetur interdum. Donec amet imperdiet eleifend<br />fringilla tincidunt. Nullam dui leo Aenean mi ligula, rhoncus ullamcorper.'

[[params.one.icon]]
icon = "fa-diamond"
style = "1"
label = "Lorem"

[[params.one.icon]]
icon = "fa-heart-o"
style = "2"
label = "Ipsum"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Dolor"

[params.two]
enable = true

[[params.two.section]]
img = "img/pic01.jpg"
title = 'Performing Ornaments<br /> title'
body = 'An interactive installation, where the visitors can create visuals while dancing with their hands'


[[params.two.section]]
img = "_MG_9084_supersmall.jpg"
title = 'Performing Ornaments'
body = 'An interactive installation, where the visitors can create visuals while dancing with their hands'

[[params.two.section]]
img = "yard super small2.png"
title = 'Live Visuals Performance'
body = 'Performing live for a dj set by Shamanic Boy at Schmiede 2021'

[[params.two.section]]
img = "herrin super small2.png"
title = 'Herrin Gedeck'
body = 'Herrin Gedeck joins female artists of various backgrounds in one performance installation exploring communication between visuals, music, sound, haiku and the body. Artists: Anna Gerlach, Konstantina Angeletou, Margarethe Maierhofer-Lischka, Sveta Schwin, Eva Esmann Behrens, Eliza Struthers Jobin. September 2021'

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Arcu accumsan"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-laptop"
title = "Ac Augue Eget"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-code"
title = "Foo bar"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-headphones"
title = "Baz kram"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-heart-o"
title = "Some latin text"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Augue consectetur sed interdum imperdiet et ipsum. Mauris lorem tincidunt nullam amet leo Aenean ligula consequat consequat."

[params.cta]
enable = true
title = "Arcue ut vel commodo"
body = "Aliquam ut ex ut augue consectetur interdum endrerit imperdiet amet eleifend fringilla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = false

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
phone = "+49 (0) 030 000 000"
address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "kona@example.com"
subject = "New Submission!"
plain = false

[params.social]
twitter = ""
facebook = "koko"
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"

[languages.de]
weight = 10
languageName = "Deutsch"
